// frontReact/products-react/src/features/products/pages/ProductsPage.jsx
// features/products/pages/ProductsPage.jsx
// Main Products page with full CRUD (mirrors Vue ProductsPage.vue)

import { RefreshCw } from 'lucide-react'
import ProductForm from '../components/ProductForm'
import ProductList from '../components/ProductList'
import { useProducts } from '../hooks/useProducts'
import { Button, Card, CardContent, CardHeader, CardTitle, Input, Label } from '../../../shared/ui'
import { useAuth } from '../../auth/hooks/useAuth'

export default function ProductsPage() {
  const auth = useAuth()
  const {
    items: products,
    errorMessage,
    busy,
    count,
    editingProduct,
    refresh,
    save,
    remove,
    startEdit,
    cancelEdit,
  } = useProducts()

  return (
    <main className="mx-auto w-full max-w-5xl px-6 py-10">
      <header className="mb-8">
        <div className="flex items-center gap-3">
          <h1 className="text-3xl font-bold tracking-tight">Products</h1>
          <span className="rounded-full bg-secondary px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
            {count} items
          </span>
        </div>
        <p className="mt-2 text-muted-foreground">
          Create, read, update and delete products from your Spring Boot backend
        </p>
      </header>

      {/* Error message */}
      {errorMessage && (
        <p className="mb-4 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
          {errorMessage}
        </p>
      )}

      {/* Auth (JWT) */}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Authentication</CardTitle>
        </CardHeader>
        <CardContent>
          {auth.errorMessage && (
            <p className="mb-3 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
              {auth.errorMessage}
            </p>
          )}

          {auth.isAuthenticated ? (
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div className="text-sm text-muted-foreground">
                Logged in as{' '}
                <span className="font-medium text-foreground">{auth.username || 'user'}</span>
                {auth.role ? <span className="text-muted-foreground"> ({auth.role})</span> : null}
              </div>
              <Button variant="outline" onClick={auth.logout}>
                Logout
              </Button>
            </div>
          ) : (
            <div className="grid gap-4 sm:grid-cols-3 sm:items-end">
              <div className="grid gap-2">
                <Label htmlFor="login-username">Username</Label>
                <Input
                  id="login-username"
                  value={auth.form.username}
                  onChange={(e) => auth.onChange('username', e.target.value)}
                  placeholder="admin"
                  autoComplete="username"
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="login-password">Password</Label>
                <Input
                  id="login-password"
                  type="password"
                  value={auth.form.password}
                  onChange={(e) => auth.onChange('password', e.target.value)}
                  placeholder="admin123"
                  autoComplete="current-password"
                />
              </div>
              <Button disabled={auth.loading} onClick={auth.login}>
                {auth.loading ? 'Signing in…' : 'Login'}
              </Button>
            </div>
          )}

          <p className="mt-3 text-xs text-muted-foreground">
            Creating, updating, and deleting products requires a JWT.
          </p>
        </CardContent>
      </Card>

      {busy && !products.length && (
        <p className="mb-4 text-sm text-muted-foreground">Loading…</p>
      )}

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        {/* CREATE + UPDATE */}
        <ProductForm
          initialProduct={editingProduct}
          busy={busy}
          onSave={save}
          onCancel={cancelEdit}
        />

        {/* READ + DELETE + choose product to edit */}
        <ProductList
          products={products}
          busy={busy}
          onEdit={startEdit}
          onDelete={remove}
        />
      </div>

      <div className="mt-6 flex justify-end">
        <Button variant="outline" disabled={busy} onClick={refresh}>
          <RefreshCw className={`mr-2 h-4 w-4 ${busy ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>
    </main>
  )
}

// frontVUE/products-ui/src/pages/ProductsPage.vue
<script setup>
// src/pages/ProductsPage.vue
// "Page" component: composes UI components and binds them to the store/composable.

import ProductForm from '../components/ProductForm.vue'
import ProductList from '../components/ProductList.vue'
import { useProducts } from '../composables/useProducts'
import { ref } from 'vue'
import { useAuth } from '../composables/useAuth'

const {
  items: products,
  errorMessage,
  loading,
  busy,
  count,
  editingProduct,
  refresh,
  startEdit,
  cancelEdit,
  save,
  remove,
} = useProducts()

const auth = useAuth()
const loginForm = ref({ username: '', password: '' })

async function onLogin() {
  await auth.login(loginForm.value)
  loginForm.value.password = ''
}
</script>

<template>
  <div class="mx-auto w-full max-w-5xl px-4 py-10">
    <header class="mb-6">
      <h1 class="text-3xl font-semibold tracking-tight">Products</h1>
      <p class="mt-1 text-sm text-white/70">Count: {{ count }}</p>
    </header>

    <!-- Auth (JWT) -->
    <section class="mb-6 rounded-xl border border-white/10 bg-white/5 p-4">
      <h2 class="text-sm font-semibold">Authentication</h2>

      <p v-if="auth.errorMessage" class="mt-3 rounded-lg border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200">
        {{ auth.errorMessage }}
      </p>

      <div v-if="auth.isAuthenticated" class="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <p class="text-sm text-white/70">
          Logged in as <span class="font-medium text-white">{{ auth.username || 'user' }}</span>
          <span v-if="auth.role" class="text-white/60"> ({{ auth.role }})</span>
        </p>
        <button
          type="button"
          class="rounded-lg border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium hover:bg-white/15"
          @click="auth.logout"
        >
          Logout
        </button>
      </div>

      <form v-else class="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3 sm:items-end" @submit.prevent="onLogin">
        <label class="grid gap-1 text-sm">
          <span class="text-white/70">Username</span>
          <input
            v-model="loginForm.username"
            class="w-full rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-sm text-white placeholder:text-white/40"
            placeholder="admin"
            autocomplete="username"
          />
        </label>

        <label class="grid gap-1 text-sm">
          <span class="text-white/70">Password</span>
          <input
            v-model="loginForm.password"
            type="password"
            class="w-full rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-sm text-white placeholder:text-white/40"
            placeholder="admin123"
            autocomplete="current-password"
          />
        </label>

        <button
          type="submit"
          class="rounded-lg border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium hover:bg-white/15 disabled:opacity-50"
          :disabled="auth.busy"
        >
          {{ auth.busy ? 'Signing in…' : 'Login' }}
        </button>
      </form>

      <p class="mt-3 text-xs text-white/50">
        Creating, updating, and deleting products requires a JWT.
      </p>
    </section>

    <!-- Status / error -->
    <p v-if="errorMessage" class="mb-4 rounded-lg border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200">
      {{ errorMessage }}
    </p>
    <p v-else-if="loading" class="mb-4 text-sm text-white/70">Loading…</p>

    <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
      <!-- CREATE + UPDATE -->
      <ProductForm
        :initial-product="editingProduct"
        :busy="busy"
        @save="save"
        @cancel="cancelEdit"
      />

      <!-- READ + DELETE + choose product to edit -->
      <ProductList
        :products="products"
        :busy="busy"
        @edit="startEdit"
        @delete="remove"
      />
    </div>

    <div class="mt-6 flex justify-end">
      <button
        type="button"
        class="rounded-lg border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium hover:bg-white/15 disabled:opacity-50"
        :disabled="busy"
        @click="refresh"
      >
        Refresh
      </button>
    </div>
  </div>
</template>
