// frontVUE/products-ui/src/pages/OrdersPage.vue
<script setup>
// src/pages/OrdersPage.vue
// Orders page: create orders + view list + reserve stock

import { useOrders } from '../composables/useOrders'
import { useProducts } from '../composables/useProducts'
import { ref, computed } from 'vue'

const {
  items: orders,
  errorMessage,
  loading,
  busy,
  count,
  refresh,
  create,
  reserve,
  updateStatus,
} = useOrders()

const { items: products } = useProducts()

// Form state
const customerName = ref('')
const orderItems = ref([{ productId: '', quantity: 1 }])

function addItem() {
  orderItems.value.push({ productId: '', quantity: 1 })
}

function removeItem(index) {
  orderItems.value.splice(index, 1)
}

const canSubmit = computed(() => {
  return customerName.value.trim() && orderItems.value.some(i => i.productId && i.quantity > 0)
})

async function submitOrder() {
  const validItems = orderItems.value
    .filter(i => i.productId && i.quantity > 0)
    .map(i => {
      const product = products.value.find(p => p.id === Number(i.productId))
      return {
        productId: Number(i.productId),
        quantity: i.quantity,
        unitPrice: product?.price || 0,
      }
    })

  await create({
    customerName: customerName.value,
    items: validItems,
  })

  // Reset form
  customerName.value = ''
  orderItems.value = [{ productId: '', quantity: 1 }]
}

function getStatusColor(status) {
  switch (status) {
    case 'CREATED': return 'bg-blue-500/20 text-blue-200 border-blue-400/30'
    case 'RESERVED': return 'bg-green-500/20 text-green-200 border-green-400/30'
    case 'CANCELLED': return 'bg-red-500/20 text-red-200 border-red-400/30'
    case 'COMPLETED': return 'bg-purple-500/20 text-purple-200 border-purple-400/30'
    default: return 'bg-white/10 text-white/70 border-white/20'
  }
}

function formatPrice(price) {
  if (price == null) return ''
  return Number(price).toFixed(2)
}

function formatDate(dateStr) {
  if (!dateStr) return ''
  return new Date(dateStr).toLocaleString()
}
</script>

<template>
  <div class="mx-auto w-full max-w-5xl px-4 py-10">
    <header class="mb-6">
      <h1 class="text-3xl font-semibold tracking-tight">Orders</h1>
      <p class="mt-1 text-sm text-white/70">Count: {{ count }}</p>
    </header>

    <!-- Error -->
    <p v-if="errorMessage" class="mb-4 rounded-lg border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200">
      {{ errorMessage }}
    </p>
    <p v-else-if="loading" class="mb-4 text-sm text-white/70">Loading…</p>

    <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
      <!-- CREATE ORDER FORM -->
      <section class="rounded-2xl border border-white/10 bg-white/5 p-6">
        <h2 class="text-lg font-semibold mb-4">Create Order</h2>

        <form @submit.prevent="submitOrder" class="space-y-4">
          <label class="grid gap-1 text-sm">
            <span class="text-white/70">Customer Name</span>
            <input
              v-model="customerName"
              class="w-full rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-sm text-white placeholder:text-white/40"
              placeholder="John Doe"
            />
          </label>

          <div class="space-y-3">
            <div class="flex items-center justify-between">
              <span class="text-sm text-white/70">Order Items</span>
              <button
                type="button"
                class="rounded-lg border border-white/15 bg-white/10 px-3 py-1 text-xs font-medium hover:bg-white/15"
                @click="addItem"
              >
                + Add Item
              </button>
            </div>

            <div
              v-for="(item, idx) in orderItems"
              :key="idx"
              class="flex gap-2 items-end"
            >
              <label class="grid gap-1 text-sm flex-1">
                <span class="text-white/70">Product</span>
                <select
                  v-model="item.productId"
                  class="w-full rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-sm text-white"
                >
                  <option value="">Select product</option>
                  <option v-for="p in products" :key="p.id" :value="p.id">
                    {{ p.name }} (${{ formatPrice(p.price) }})
                  </option>
                </select>
              </label>

              <label class="grid gap-1 text-sm w-24">
                <span class="text-white/70">Qty</span>
                <input
                  v-model.number="item.quantity"
                  type="number"
                  min="1"
                  class="w-full rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-sm text-white"
                />
              </label>

              <button
                v-if="orderItems.length > 1"
                type="button"
                class="rounded-lg border border-red-400/30 bg-red-500/10 px-3 py-2 text-sm text-red-200 hover:bg-red-500/15"
                @click="removeItem(idx)"
              >
                ×
              </button>
            </div>
          </div>

          <button
            type="submit"
            :disabled="!canSubmit || busy"
            class="w-full rounded-lg border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium hover:bg-white/15 disabled:opacity-50"
          >
            {{ busy ? 'Creating…' : 'Create Order' }}
          </button>
        </form>
      </section>

      <!-- ORDERS LIST -->
      <section class="rounded-2xl border border-white/10 bg-white/5 p-6">
        <h2 class="text-lg font-semibold mb-4">Orders List</h2>

        <p v-if="orders.length === 0" class="text-sm text-white/70">
          No orders yet.
        </p>

        <ul v-else class="space-y-4 max-h-[500px] overflow-y-auto">
          <li
            v-for="order in orders"
            :key="order.id"
            class="rounded-xl border border-white/10 bg-white/5 p-4"
          >
            <div class="flex items-start justify-between gap-3">
              <div class="min-w-0">
                <div class="flex flex-wrap items-center gap-2">
                  <span class="font-semibold">Order #{{ order.id }}</span>
                  <span
                    class="rounded-full px-2 py-0.5 text-xs font-medium border"
                    :class="getStatusColor(order.status)"
                  >
                    {{ order.status }}
                  </span>
                </div>
                <p class="mt-1 text-sm text-white/70">{{ order.customerName }}</p>
                <p class="text-xs text-white/50">{{ formatDate(order.createdAt) }}</p>
              </div>
              <p class="text-sm font-semibold shrink-0">${{ formatPrice(order.total) }}</p>
            </div>

            <!-- Items -->
            <div v-if="order.items?.length" class="mt-3 text-xs text-white/60">
              <span v-for="(item, i) in order.items" :key="item.id">
                {{ item.quantity }}x Product#{{ item.productId }}{{ i < order.items.length - 1 ? ', ' : '' }}
              </span>
            </div>

            <!-- Actions -->
            <div class="mt-3 flex flex-wrap gap-2">
              <button
                v-if="order.status === 'CREATED'"
                :disabled="busy"
                class="rounded-lg border border-green-400/30 bg-green-500/10 px-3 py-1.5 text-xs font-medium text-green-200 hover:bg-green-500/15 disabled:opacity-50"
                @click="reserve(order.id)"
              >
                Reserve Stock
              </button>
              <button
                v-if="order.status === 'RESERVED'"
                :disabled="busy"
                class="rounded-lg border border-purple-400/30 bg-purple-500/10 px-3 py-1.5 text-xs font-medium text-purple-200 hover:bg-purple-500/15 disabled:opacity-50"
                @click="updateStatus(order.id, 'COMPLETED')"
              >
                Complete
              </button>
              <button
                v-if="order.status !== 'CANCELLED' && order.status !== 'COMPLETED'"
                :disabled="busy"
                class="rounded-lg border border-red-400/30 bg-red-500/10 px-3 py-1.5 text-xs font-medium text-red-200 hover:bg-red-500/15 disabled:opacity-50"
                @click="updateStatus(order.id, 'CANCELLED')"
              >
                Cancel
              </button>
            </div>
          </li>
        </ul>
      </section>
    </div>

    <div class="mt-6 flex justify-end">
      <button
        type="button"
        class="rounded-lg border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium hover:bg-white/15 disabled:opacity-50"
        :disabled="busy"
        @click="refresh"
      >
        Refresh
      </button>
    </div>
  </div>
</template>

// frontReact/products-react/src/features/orders/pages/OrdersPage.jsx
// features/orders/pages/OrdersPage.jsx
// Orders page with create + list + reserve stock functionality

import { useState } from 'react'
import { RefreshCw, Plus, X, ShoppingCart, Package, CheckCircle, XCircle } from 'lucide-react'
import { useOrders } from '../hooks/useOrders'
import { useProducts } from '../../products/hooks/useProducts'
import { Button, Card, CardContent, CardHeader, CardTitle, Input, Label } from '../../../shared/ui'

export default function OrdersPage() {
  const { items: orders, errorMessage, busy, count, refresh, create, reserve, updateStatus } = useOrders()
  const { items: products } = useProducts()

  // Form state
  const [customerName, setCustomerName] = useState('')
  const [orderItems, setOrderItems] = useState([{ productId: '', quantity: 1 }])

  const addItem = () => {
    setOrderItems([...orderItems, { productId: '', quantity: 1 }])
  }

  const removeItem = (index) => {
    setOrderItems(orderItems.filter((_, i) => i !== index))
  }

  const updateItem = (index, field, value) => {
    const updated = [...orderItems]
    updated[index] = { ...updated[index], [field]: value }
    setOrderItems(updated)
  }

  const canSubmit = customerName.trim() && orderItems.some((i) => i.productId && i.quantity > 0)

  const handleSubmit = async (e) => {
    e.preventDefault()
    const validItems = orderItems
      .filter((i) => i.productId && i.quantity > 0)
      .map((i) => {
        const product = products.find((p) => p.id === Number(i.productId))
        return {
          productId: Number(i.productId),
          quantity: Number(i.quantity),
          unitPrice: product?.price || 0,
        }
      })

    await create({
      customerName,
      items: validItems,
    })

    // Reset form
    setCustomerName('')
    setOrderItems([{ productId: '', quantity: 1 }])
    refresh()
  }

  const getStatusStyle = (status) => {
    switch (status) {
      case 'CREATED':
        return 'bg-blue-500/20 text-blue-300 border-blue-500/30'
      case 'RESERVED':
        return 'bg-green-500/20 text-green-300 border-green-500/30'
      case 'CANCELLED':
        return 'bg-destructive/20 text-destructive border-destructive/30'
      case 'COMPLETED':
        return 'bg-purple-500/20 text-purple-300 border-purple-500/30'
      default:
        return 'bg-secondary text-muted-foreground border-border'
    }
  }

  const formatPrice = (price) => (price != null ? Number(price).toFixed(2) : '')
  const formatDate = (dateStr) => (dateStr ? new Date(dateStr).toLocaleString() : '')

  return (
    <main className="mx-auto w-full max-w-5xl px-6 py-10">
      <header className="mb-8">
        <div className="flex items-center gap-3">
          <ShoppingCart className="h-8 w-8 text-muted-foreground" />
          <h1 className="text-3xl font-bold tracking-tight">Orders</h1>
          <span className="rounded-full bg-secondary px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
            {count} orders
          </span>
        </div>
        <p className="mt-2 text-muted-foreground">Create orders, reserve stock (via gRPC), and manage lifecycle</p>
      </header>

      {/* Error message */}
      {errorMessage && (
        <p className="mb-4 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
          {errorMessage}
        </p>
      )}

      <div className="grid gap-6 lg:grid-cols-2">
        {/* CREATE ORDER FORM */}
        <Card>
          <CardHeader>
            <CardTitle>Create Order</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="customerName">Customer Name</Label>
                <Input
                  id="customerName"
                  value={customerName}
                  onChange={(e) => setCustomerName(e.target.value)}
                  placeholder="John Doe"
                />
              </div>

              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <Label>Order Items</Label>
                  <Button type="button" variant="outline" size="sm" onClick={addItem}>
                    <Plus className="mr-1 h-3 w-3" />
                    Add Item
                  </Button>
                </div>

                {orderItems.map((item, idx) => (
                  <div key={idx} className="flex gap-2 items-end">
                    <div className="grid gap-2 flex-1">
                      <Label className="text-xs text-muted-foreground">Product</Label>
                      <select
                        value={item.productId}
                        onChange={(e) => updateItem(idx, 'productId', e.target.value)}
                        className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                      >
                        <option value="">Select product</option>
                        {products.map((p) => (
                          <option key={p.id} value={p.id}>
                            {p.name} (${formatPrice(p.price)})
                          </option>
                        ))}
                      </select>
                    </div>

                    <div className="grid gap-2 w-24">
                      <Label className="text-xs text-muted-foreground">Qty</Label>
                      <Input
                        type="number"
                        min="1"
                        value={item.quantity}
                        onChange={(e) => updateItem(idx, 'quantity', e.target.value)}
                      />
                    </div>

                    {orderItems.length > 1 && (
                      <Button type="button" variant="destructive" size="icon" onClick={() => removeItem(idx)}>
                        <X className="h-4 w-4" />
                      </Button>
                    )}
                  </div>
                ))}
              </div>

              <Button type="submit" disabled={!canSubmit || busy} className="w-full">
                {busy ? 'Creating…' : 'Create Order'}
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* ORDERS LIST */}
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle>Orders List</CardTitle>
            <Button variant="outline" size="sm" onClick={refresh} disabled={busy}>
              <RefreshCw className={`mr-1 h-3 w-3 ${busy ? 'animate-spin' : ''}`} />
              Refresh
            </Button>
          </CardHeader>
          <CardContent>
            {orders.length === 0 ? (
              <p className="text-sm text-muted-foreground">No orders yet.</p>
            ) : (
              <div className="space-y-4 max-h-[500px] overflow-y-auto pr-2">
                {orders.map((order) => (
                  <div key={order.id} className="rounded-lg border border-border/50 bg-card/50 p-4">
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="font-semibold">Order #{order.id}</span>
                          <span className={`rounded-full border px-2 py-0.5 text-xs font-medium ${getStatusStyle(order.status)}`}>
                            {order.status}
                          </span>
                        </div>
                        <p className="mt-1 text-sm text-muted-foreground">{order.customerName}</p>
                        <p className="text-xs text-muted-foreground">{formatDate(order.createdAt)}</p>
                      </div>
                      <p className="text-sm font-semibold shrink-0">${formatPrice(order.total)}</p>
                    </div>

                    {/* Items */}
                    {order.items?.length > 0 && (
                      <div className="mt-3 flex items-center gap-1 text-xs text-muted-foreground">
                        <Package className="h-3 w-3" />
                        {order.items.map((item, i) => (
                          <span key={item.id}>
                            {item.quantity}x Product#{item.productId}
                            {i < order.items.length - 1 ? ', ' : ''}
                          </span>
                        ))}
                      </div>
                    )}

                    {/* Actions */}
                    <div className="mt-3 flex flex-wrap gap-2">
                      {order.status === 'CREATED' && (
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={busy}
                          onClick={() => reserve(order.id).then(refresh)}
                          className="border-green-500/30 bg-green-500/10 text-green-300 hover:bg-green-500/20"
                        >
                          <CheckCircle className="mr-1 h-3 w-3" />
                          Reserve Stock
                        </Button>
                      )}
                      {order.status === 'RESERVED' && (
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={busy}
                          onClick={() => updateStatus(order.id, 'COMPLETED').then(refresh)}
                          className="border-purple-500/30 bg-purple-500/10 text-purple-300 hover:bg-purple-500/20"
                        >
                          Complete
                        </Button>
                      )}
                      {order.status !== 'CANCELLED' && order.status !== 'COMPLETED' && (
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={busy}
                          onClick={() => updateStatus(order.id, 'CANCELLED').then(refresh)}
                          className="border-destructive/30 bg-destructive/10 text-destructive hover:bg-destructive/20"
                        >
                          <XCircle className="mr-1 h-3 w-3" />
                          Cancel
                        </Button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
